name: flowcy_win
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.6
  - pip
#   - intel-openmp
#   - vs2008_runtime
  - numpy
  - scikit-learn
  - pillow=5.2.0
  - pytorch=1.8.1
  - torchvision=0.9.1
  - torchaudio=0.8.1
  - cudatoolkit=10.2
  - scanpy=1.7.2
  - anndata=0.7.6
#   - python-igraph
#   - leidenalg
#   - anndata
#   - pandas
#   - matplotlib
#   - seaborn
#   - scipy
#   - statsmodels
#   - networkx
#   - numba
#   - umap-learn
  - pip:
      - somoclu==1.7.5
      - flowio
      - pytometry
