
pipeline_load_path: "./results/test/test_cli/00"
pipeline_filename: "trained_gating_pipeline_00.pkl"

data_file_path: "./data/raw/test"  # default: cwd
data_file_names: ["ER_000000_H1_150305_ED.fcs", ]  # default: listdir(path)
gate: true
dim_red_methods: ["som", "pca", "umap"]
dim_red_method_kwargs:
  - null
  -
    whiten: false
  -
    n_neighbors: 5
    n_jobs: 16

save_sample_wise: false  # whether to save to individual or one fcs file
save_path: "./results/test/test_cli"
save_filenames: null
val_range: [0.0, 1048576.0]
keep_unscaled: true
fcs_metadata_dicts: null